name: Java-CI-with-Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_VERSION: '17'

jobs:
  build-and-test:
    name: Checkstyle, Unit tests, Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Run Checkstyle
      run: mvn -B checkstyle:check

    - name: Run tests + Coverage Check (80% minimum)
      run: mvn clean verify

  docker-build-push:
    name: Docker build and push
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Build Maven project (skip tests)
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract module names
        id: modules
        run: |
          MODULES=$(find . -name "pom.xml" -exec dirname {} \; | grep -v "/target" | sort)
          echo "modules=$MODULES" >> $GITHUB_OUTPUT

      - name: Build and push each module
        run: |
          for MODULE_DIR in ${{ steps.modules.outputs.modules }}; do
            MODULE_NAME=$(basename "$MODULE_DIR")
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/$MODULE_NAME

            echo "➡️ Building and pushing $IMAGE_NAME..."

            # Собираем и загружаем образ
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag "$IMAGE_NAME:latest" \
              --tag "$IMAGE_NAME:${{ github.sha }}" \
              --file "$MODULE_DIR/Dockerfile" \
              --push true \
              "$MODULE_DIR"

            echo "✅ Pushed $IMAGE_NAME:latest and $IMAGE_NAME:${{ github.sha }}"
          done
